"""add ai_generated value to task_source_enum

Revision ID: 0009
Revises: 0008
Create Date: 2026-04-21

Adds 'ai_generated' as a new valid value for the task_source_enum type.

Tasks generated by the AI Task Generator feature are saved with
source='ai_generated' so they can be filtered separately from
GitHub-scraped tasks (source='github_scrape') and manually posted
tasks (source='manual_post').

ALTER TYPE ... ADD VALUE IF NOT EXISTS is idempotent and safe to re-run.
Note: PostgreSQL does not support removing enum values without dropping
and recreating the type, so downgrade is intentionally a no-op.
"""

from alembic import op
import sqlalchemy as sa

revision = "0009"
down_revision = "0008"
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()
    conn.execute(sa.text("""
        ALTER TYPE task_source_enum ADD VALUE IF NOT EXISTS 'ai_generated';
    """))


def downgrade() -> None:
    # PostgreSQL does not support dropping individual enum values.
    # The extra 'ai_generated' value causes no harm if unused, so this is a
    # safe no-op. To fully revert, the enum would need to be recreated.
    pass
